const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Addidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 100,
            brand: 'Addidas',
            rating: 5,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        } 
    ]
}
export default data;